-- 정규화 계약 2판의 두 분석 테이블 (ADR 0020). 이 파일이 두 테이블 스키마의 진실원이고,
-- 이 위치가 곧 쓰기 소유의 근거다 (ADR 0008 규칙 1 의 판정법 · ADR 0015).
--
-- 로그와 선별된 스팬은 telemetry_events, 모든 OTLP metric point 는 telemetry_metric_points 에
-- 들어간다. 두 테이블의 앞 49 컬럼(tenant_id 부터 enrichment_json 까지)은 같은 봉투다 — 봉투를
-- 고칠 때는 두 테이블을 같은 커밋에서 고친다. 컬럼별 의미와 어휘는 ADR 0020 이 담는다.
--
-- 번호가 V2 인 것은 V1 이 enriched_events 이기 때문이다. 새 테이블은 새 파일로 더하고 V1 은
-- 그대로 둔다.
--
-- ⚠️ **모든 문장은 IF NOT EXISTS 형태여야 한다** (ADR 0015). 매 기동마다 V1 부터 전부 다시
-- 실행된다. 이 파일이 배포된 뒤에는 고치지 말고 다음 번호 파일에
-- ALTER TABLE ... ADD COLUMN IF NOT EXISTS 를 쓴다. 정렬 키·타입 변경은 멱등으로 적을 수 없다.
--
-- 엔진 ReplacingMergeTree(row_version) → 관측(observation_id)당 row_version 이 가장 큰 행
-- 하나가 남는다. 병합 전에도 같은 결과를 보려면 조회는 FINAL 이 필요하고, 기본키 밖의 조건은
-- FINAL 뒤에 적용된다 (ADR 0020 §7). base table 을 FINAL 없이 합산하지 않는다.

CREATE TABLE IF NOT EXISTS telemetry_events
(
    tenant_id LowCardinality(String),
    installation_id String,
    observation_id FixedString(64),
    row_version UInt64,
    normalizer_rev UInt32,
    analysis_hash FixedString(64),
    schema_version UInt16 DEFAULT 1,
    identity_version String,
    source_identity_kind LowCardinality(String),
    source_identity_namespace Nullable(String),
    native_observation_id Nullable(String),
    record_status LowCardinality(String),
    exclusion_reason Nullable(String),
    mapping_status LowCardinality(String),
    quality_flags Array(LowCardinality(String)),
    source_time DateTime64(9, 'UTC') CODEC(Delta, ZSTD),
    source_time_origin LowCardinality(String),
    event_time Nullable(DateTime64(9, 'UTC')),
    observed_time Nullable(DateTime64(9, 'UTC')),
    received_time DateTime64(9, 'UTC'),
    signal LowCardinality(String),
    product LowCardinality(String),
    surface LowCardinality(String),
    product_version Nullable(String),
    service_name Nullable(String),
    service_version Nullable(String),
    service_instance_id Nullable(String),
    scope_name Nullable(String),
    scope_version Nullable(String),
    resource_schema_url Nullable(String),
    scope_schema_url Nullable(String),
    original_name Nullable(String),
    mapping_version String,
    enrichment_version String,
    usage_role LowCardinality(String),
    usage_scope LowCardinality(String),
    workload_kind LowCardinality(String),
    session_id Nullable(String),
    session_id_namespace Nullable(String),
    model Nullable(String),
    member_id Nullable(String),
    team_id_as_of Nullable(String),
    team_ids_as_of Array(String),
    archive_ref Nullable(String),
    archive_selector Nullable(String),
    masking_version String,
    metadata_json String CODEC(ZSTD(3)),
    attrs Map(LowCardinality(String), String),
    enrichment_json String CODEC(ZSTD(3)),
    event_type LowCardinality(String),
    operation LowCardinality(String),
    end_time Nullable(DateTime64(9, 'UTC')),
    duration_ns Nullable(Int64),
    ttft_ns Nullable(Int64),
    ttft_scope LowCardinality(String),
    turn_id Nullable(String),
    turn_id_namespace Nullable(String),
    request_id Nullable(String),
    request_id_namespace Nullable(String),
    client_request_id Nullable(String),
    client_request_id_namespace Nullable(String),
    response_id Nullable(String),
    response_id_namespace Nullable(String),
    call_id Nullable(String),
    call_id_namespace Nullable(String),
    tool_result_seq Nullable(Int64),
    trace_id Nullable(String),
    span_id Nullable(String),
    parent_span_id Nullable(String),
    span_kind LowCardinality(String),
    span_status_code LowCardinality(String),
    severity_number Nullable(UInt8),
    tokens_input Nullable(Int64),
    tokens_output Nullable(Int64),
    tokens_cache_read Nullable(Int64),
    tokens_cache_create Nullable(Int64),
    tokens_reasoning Nullable(Int64),
    tokens_tool Nullable(Int64),
    tokens_total_reported Nullable(Int64),
    tokens_total_derived Nullable(Int64),
    tokens_input_uncached Nullable(Int64),
    input_semantics LowCardinality(String),
    output_semantics LowCardinality(String),
    semantics_profile Nullable(String),
    cost_reported_usd Nullable(Decimal(38, 12)),
    cost_estimated_usd Nullable(Decimal(38, 12)),
    reported_cost_basis LowCardinality(String),
    pricing_version Nullable(String),
    success Nullable(Bool),
    http_status Nullable(UInt16),
    error_type LowCardinality(String),
    attempt Nullable(Int64),
    tool_name Nullable(String),
    tool_namespace Nullable(String),
    tool_origin LowCardinality(String),
    tool_action LowCardinality(String),
    mcp_server Nullable(String),
    decision LowCardinality(String),
    decision_raw Nullable(String),
    decision_source LowCardinality(String),
    decision_scope LowCardinality(String),
    prompt_length Nullable(Int64),
    response_length Nullable(Int64),
    command_name Nullable(String),
    stop_reason LowCardinality(String),
    reasoning_effort LowCardinality(String),
    agent_id Nullable(String),
    INDEX idx_installation installation_id TYPE bloom_filter GRANULARITY 4,
    INDEX idx_session session_id TYPE bloom_filter GRANULARITY 4,
    INDEX idx_event_type event_type TYPE set(128) GRANULARITY 4
)
ENGINE = ReplacingMergeTree(row_version)
PARTITION BY toYYYYMM(source_time)
ORDER BY (tenant_id, source_time, installation_id, observation_id);

CREATE TABLE IF NOT EXISTS telemetry_metric_points
(
    tenant_id LowCardinality(String),
    installation_id String,
    observation_id FixedString(64),
    row_version UInt64,
    normalizer_rev UInt32,
    analysis_hash FixedString(64),
    schema_version UInt16 DEFAULT 1,
    identity_version String,
    source_identity_kind LowCardinality(String),
    source_identity_namespace Nullable(String),
    native_observation_id Nullable(String),
    record_status LowCardinality(String),
    exclusion_reason Nullable(String),
    mapping_status LowCardinality(String),
    quality_flags Array(LowCardinality(String)),
    source_time DateTime64(9, 'UTC') CODEC(Delta, ZSTD),
    source_time_origin LowCardinality(String),
    event_time Nullable(DateTime64(9, 'UTC')),
    observed_time Nullable(DateTime64(9, 'UTC')),
    received_time DateTime64(9, 'UTC'),
    signal LowCardinality(String),
    product LowCardinality(String),
    surface LowCardinality(String),
    product_version Nullable(String),
    service_name Nullable(String),
    service_version Nullable(String),
    service_instance_id Nullable(String),
    scope_name Nullable(String),
    scope_version Nullable(String),
    resource_schema_url Nullable(String),
    scope_schema_url Nullable(String),
    original_name Nullable(String),
    mapping_version String,
    enrichment_version String,
    usage_role LowCardinality(String),
    usage_scope LowCardinality(String),
    workload_kind LowCardinality(String),
    session_id Nullable(String),
    session_id_namespace Nullable(String),
    model Nullable(String),
    member_id Nullable(String),
    team_id_as_of Nullable(String),
    team_ids_as_of Array(String),
    archive_ref Nullable(String),
    archive_selector Nullable(String),
    masking_version String,
    metadata_json String CODEC(ZSTD(3)),
    attrs Map(LowCardinality(String), String),
    enrichment_json String CODEC(ZSTD(3)),
    series_id Nullable(FixedString(64)),
    series_identity_status LowCardinality(String),
    structural_status LowCardinality(String),
    metric_name String,
    metric_type LowCardinality(String),
    metric_family LowCardinality(String),
    metric_profile Nullable(String),
    description Nullable(String),
    raw_unit String,
    canonical_unit LowCardinality(String),
    token_component LowCardinality(String),
    temporality LowCardinality(String),
    temporality_code Nullable(Int32),
    is_monotonic Nullable(Bool),
    start_time Nullable(DateTime64(9, 'UTC')),
    value_int Nullable(Int64),
    value_double Nullable(Float64),
    hist_count Nullable(UInt64),
    hist_sum Nullable(Float64),
    hist_min Nullable(Float64),
    hist_max Nullable(Float64),
    hist_buckets_present Bool,
    explicit_bounds Array(Float64),
    bucket_counts Array(UInt64),
    exp_scale Nullable(Int32),
    exp_zero_count Nullable(UInt64),
    exp_zero_threshold Nullable(Float64),
    exp_positive_offset Nullable(Int32),
    exp_positive_buckets Array(UInt64),
    exp_negative_offset Nullable(Int32),
    exp_negative_buckets Array(UInt64),
    summary_count Nullable(UInt64),
    summary_sum Nullable(Float64),
    quantiles Array(Float64),
    quantile_values Array(Float64),
    point_flags UInt32,
    INDEX idx_installation installation_id TYPE bloom_filter GRANULARITY 4,
    INDEX idx_session session_id TYPE bloom_filter GRANULARITY 4,
    INDEX idx_metric_name metric_name TYPE set(256) GRANULARITY 4
)
ENGINE = ReplacingMergeTree(row_version)
PARTITION BY toYYYYMM(source_time)
ORDER BY (tenant_id, source_time, installation_id, observation_id);
